name: CI | Sync develop to approval

on:
  push:
    branches:
      - develop

permissions:
  contents: write

concurrency:
  group: sync-develop-approval
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync approval
        run: |
          git init
          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          git fetch origin develop
          git push origin FETCH_HEAD:approval --force-with-lease